NEXT_PUBLIC_SUPABASE_URL=https://mjsaxvuewmijayadofgw.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qc2F4dnVld21pamF5YWRvZmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDgwNjYzOTEsImV4cCI6MTk2MzY0MjM5MX0.QRfWtvAvjVoeFjdEWLKbm09c5l0NNrqQL3e5sCJG_BY
